CREATE TABLE USERS (
  userId VARCHAR(255) PRIMARY KEY,
  userName VARCHAR(255) UNIQUE,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  roles VARCHAR(15) DEFAULT 'user',
  emailSent INT DEFAULT 0,
  isDeleted INT DEFAULT 0,
  isReset INT DEFAULT 0
);

CREATE TABLE QUESTIONS (
  questionsId VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) REFERENCES USERS(userId),
  title VARCHAR(255),
  body TEXT,
  isDeleted INT DEFAULT 0
);

CREATE TABLE ANSWERS (
  answerId VARCHAR(255) PRIMARY KEY,
  questionsId VARCHAR(255) REFERENCES QUESTIONS(questionsId),
  body TEXT,
  userId VARCHAR(255) REFERENCES USERS(userId),
  isPreferred INT DEFAULT 0,
);

ALTER TABLE ANSWERS
ADD isDeleted INT DEFAULT 0;



SELECT * FROM ANSWERS

CREATE TABLE COMMENTS (
  commentId VARCHAR(255) PRIMARY KEY,
  userId VARCHAR(255) REFERENCES USERS(userId),
  questionsId VARCHAR(255) REFERENCES QUESTIONS(questionsId),
  answerId VARCHAR(255) REFERENCES ANSWERS(answerId),
  body TEXT,
  isDeleted INT DEFAULT 0
);

CREATE TABLE VOTES (
  voteId VARCHAR(255) PRIMARY KEY,
  answerId VARCHAR(255) REFERENCES ANSWERS(answerId),
  userId VARCHAR(255) REFERENCES USERS(userId),
  upVotes INT DEFAULT 0,
  downVotes INT DEFAULT 0
);
ALTER TABLE  VOTES
ADD isDeleted INT DEFAULT 0;

CREATE TABLE TAGS (
  tagId VARCHAR(255) PRIMARY KEY,
  tagName VARCHAR(255),
  body TEXT
  isDeleted INT DEFAULT 0;
);
ALTER TABLE TAGS
ADD isDeleted INT DEFAULT 0;

CREATE TABLE QUESTIONTAGS (
  tagId VARCHAR(255) REFERENCES TAGS(tagId),
  questionsId VARCHAR(255) REFERENCES QUESTIONS(questionsId)
);
