###
POST   http://localhost:4000/users
Content-Type: application/json


{
    "userName":"sue",
    "email":"susanmwangi3030@gmail.com",
    "password":"Wamuyu@2023"
}

//get all users
###
GET   http://localhost:4000/users


// get one user by email
###
GET  http://localhost:4000/users/email/muchoki@gmail.com


// get user by ID
###
GET   http://localhost:4000/users/1234a


//Update user
###
PUT  http://localhost:4000/users/a5ebd33b-1dec-4069-b20e-d29acce84a9a
Content-Type: application/json

{
    "userName":"loveyours",
    "email":"sunday@gmail.com",
    "password":"Wamuyu@2023"
}

//delete user
###
DELETE http://localhost:4000/users/1234a
Content-Type:application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NWIwYzc5Ni1iMzNlLTQ1ZDgtYmRhMy03MmMyNjNmYzg5NDciLCJ1c2VyTmFtZSI6IlNvbnlhIiwiZW1haWwiOiJTb255YUBnbWFpbC5jb20iLCJyb2xlcyI6InVzZXIiLCJpc1Jlc2V0IjowLCJpYXQiOjE2ODcxMDQ3Njh9.nsij411DYfFwsLwjVYe_MmgyP_8rSW1Yo_Zhe-WaPCc

//login
###
POST http://localhost:4000/users/login
Content-Type: application/json

{
    
    "email":"Sonya@gmail.com",
    "password":"Wamuyu@2023"

}


//add question
###
POST http://localhost:4000/questions/06768a7f-5883-4df0-8a19-2040e9970ab1
Content-Type: application/json

{
  "title": "DLDLDLDLD",
  "body": "TJDHFUUJFUJFJUF",
  "TAGS":[{"tagId":2,"tagName":"HTML"}]
}

//get all questions
###
GET http://localhost:4000/questions

//get one question by ID
###
GET  http://localhost:4000/questions/f9ea80e6-2da7-48a7-9d81-5f726b4c7017


//get  questions by userid
###
GET  http://localhost:4000/questions/user/06768a7f-5883-4df0-8a19-2040e9970ab1


// delete question by ID
###
DELETE  http://localhost:4000/questions/06768a7f-5883-4df0-8a19-2040e9970ab1/2d074d7f-4e01-4361-a184-a108dc0482a6

//Update a question  userid/questionsid
###
PUT  http://localhost:4000/questions/9c867fbd-a697-4ca2-8075-dc29c46df51e/f9ea80e6-2da7-48a7-9d81-5f726b4c7017
Content-Type: application/json

{
  "title": "it works but why",
  "body": "jijijijiji",
  "TAGS":[{"tagId":4,"tagName":"JavaScript"}]
}


//add answer
###
POST http://localhost:4000/answer/9c867fbd-a697-4ca2-8075-dc29c46df51e/f9ea80e6-2da7-48a7-9d81-5f726b4c7017
Content-Type: application/json

{
 "body":"Hey i think ik what you didi wrong lemme show you how its done in a few"
}

//set preferred
###
POST  http://localhost:4000/answer/805cc6d1-aec5-43ac-8ea8-966681848a99
Content-Type: application/json

{
  "isPreferred":"1"
}

//get answers for a  question by using questionId
###
GET  http://localhost:4000/answer/f9ea80e6-2da7-48a7-9d81-5f726b4c7017

###
//get one question posted by user
GET  http://localhost:4000/answer/9c867fbd-a697-4ca2-8075-dc29c46df51e


//add comment
###
POST  http://localhost:4000/comments/9c867fbd-a697-4ca2-8075-dc29c46df51e/805cc6d1-aec5-43ac-8ea8-966681848a99
Content-Type: application/json

{
  "body":"why oh why"
}
//get one comment 

//get all comments